name: 'Slack Notify Build'
description: 'Report GitHub Actions build status on Slack'
branding:
  icon: message-square
  color: orange
inputs:
  channel:
    description: 'The Slack channel name. Required if no `channel_id` provided.'
    required: false
  channel_id:
    description: 'The Slack channel ID. Required if no `channel` provided.'
    required: false
  start:
    description: 'The status to list in the update.'
    required: false
    default: false
  finish:
    description: 'The status to list in the update.'
    required: false
    default: false
  success:
    description: 'The status to list in the update.'
    required: false
    default: false
  failure:
    description: 'The status to list in the update.'
    required: false
    default: false
  version:
    description: 'Generated version'
    required: false
    default: ''

  message_id:
    description: 'The ID of the existing Slack message to update.'
    required: false
outputs:
  message_id:
    description: 'The unique timestamp identifier of the Slack message sent'
runs:
  using: 'node12'
  main: 'dist/index.js'
